import { join } from 'path';

import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

import { AppModule } from './app.module';

/**
 * Bootstrap the backend application
 */
async function bootstrap(): Promise<void> {
  // Create application
  const app: NestExpressApplication = await NestFactory.create(AppModule);

  // Configure Swagger
  const options = new DocumentBuilder()
    .setTitle('Hello World API - Swagger')
    .setDescription('REST API description')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('/swagger', app, document);

  // WORKAROUND:
  // We serve the "static" folder (generated by "ncc") behind the "/swagger" URL so that all Swagger UI assets get fetched properly
  app.useStaticAssets(join(__dirname, '/static'), {
    prefix: '/swagger',
  });

  // Start application
  await app.listen(3000);
  console.info(`Backend application is available at "http://localhost:3000".`);
}

// Run!!
bootstrap();
